### ISSUE TITLE
vscode-openapi causing issues with vscode-cpptools extension

### ISSUE THREAD

**Issue by nvmker** [42Crunch/vscode-openapi#107]
Hi,
Looks like vscode-openapi extension causing issues with vscode-cpptools extension, in particular with loading JSON files with particular schema related to cpptools.
You can find full conversation here:
https://github.com/microsoft/vscode-cpptools/issues/6841
Let me know if I need to run debugger or something.

**Comment by ak1394** [comment]
Hi @nvmker !

It appears that this issue is caused by a bug in VS Code.

Reason why our extension triggers this bug is as follows: in order to provide schema validation for all OpenAPI JSON files (which can have any name, but have .json extension) we contribute a schema to all file which match "*.json" pattern.

At the same time the CPP extension contributes schema for a file named "c_cpp_properties.json".

When c_cpp_properties.json file is handled by VS Code it needs to combine these two schemas and use the resulting schema to perform validation.

However, it seems that VS Code is failing to do it (and you can see the trace of it in the message referring to "schemaservice" and "combinedschema" in the error).

To illustrate the issue I have created a minimal extension which simply contributes a schema for "*.json" files, and doesn't do much besides it. If you install this extension along with CPP one you'll see the same problem as with vscode-openapi. The extension is here: https://github.com/42Crunch/vscode-minimal-issue-107 

I couldn't find the relevant place in VS Code where the problem arises, but I think this info is a good start to open a bug for VS Code. Would you be willing to do it, since the issue seems to be affecting vscode-cpptools more directly than vscode-openapi?

**Comment by nvmker** [comment]
Thanks for the info, I will open a bug report.

**Comment by aeschli** [comment]
I'll be looking why VSCode has problems with the combined schema.

That said, a schema contribution for `*.json` is not a good idea. I will affect all json files. Please make the pattern more specific.

**Comment by ak1394** [comment]
Hi @aeschli ! 

I would happily stop contributing schemas for "*.json", but I don't think there is currently a way to contribute a schema to a specific json file on demand? There was some discussion in https://github.com/microsoft/vscode/issues/69868 bit it got closed.

In case of YAML we use schema contributor API https://github.com/redhat-developer/vscode-yaml/wiki/Extension-API but I'm not aware of a similar mechanism for JSON files?

**Comment by aeschli** [comment]
microsoft/vscode#69868 is about language detection, in case you want to have your own language (something like json-openapi).
https://github.com/microsoft/vscode/issues/69868#issuecomment-490084449 describes how you can do that.
With your own language you have to reimplement some of the language capabilities of JSON (grammar and language support) That's a bit of work, but doable as the rich language features are reusable through https://github.com/microsoft/vscode-json-languageservice/

If you want to stick with JSON I recommend to propagate your own file suffix (.openapi.json) or add the `$schema` property to your json files.

**Comment by ak1394** [comment]
Thanks for suggestion! You're correct that implementing a custom language is more work, and at this stage we've settled with providing a schema to json language. 

Unfortunately, we're not in position to request users to rename the files or add $schema to the file contents, as OpenAPI is an established standard https://www.openapis.org/ and user base is simply too big for requests like that.
