### ISSUE TITLE
Certificate expired error

### ISSUE THREAD

**Issue by GravlLift** [42Crunch/vscode-openapi#155]
When referencing an external schema, specifically https://zalando.github.io/problem/schema.yaml#/Problem, I receive the following exception:

```
Error reading file "https://opensource.zalando.com/problem/schema.yaml: cannot open openapi-internal-https://opensource.zalando.com/problem/schema.yaml. Detail: certificate has expired"
```

Minimal reproduction:
```yaml
openapi: 3.0.0
info:
  version: '1.0.0'
  title: 'Test'
paths:
  /test:
    get:
      responses:
        default:
          description: test
components:
  responses:
    Error:
      description: Unexpected error
      content:
        application/problem+json:
          schema:
            $ref: 'https://opensource.zalando.com/problem/schema.yaml#/Problem'
```

Viewing the certificate for that URL in my browser, the certificate looks to have a valid period of 2021-12-17 to 2022-03-17, which should be valid for the current date.

**Comment by ak1394** [comment]
This is likely caused by an outstanding VS Code issue https://github.com/microsoft/vscode/issues/136787 which will be resolved when VS Code is updated to use newer electron version, presumably some time in Feb.

In the meantime a workaround of adding `"http.systemCertificates": false` to your VS Code settings.json should help.

**Comment by GravlLift** [comment]
@ak1394, disabling the system certificate fixed the issue, thanks.
