### ISSUE TITLE
[BUG] Relative Endpoint URLs not recognized

### ISSUE THREAD

**Issue by azusa0127** [42Crunch/vscode-openapi#17]
https://swagger.io/docs/specification/authentication/oauth2/

In OpenAPI 3.0, `authorizationUrl`, `tokenUrl` and `refreshUrl` can be specified relative to the API server URL. This is handy if these endpoints are on same server as the rest of the API operations.

The plugin treats those as Errors like:
```
String is not a URI: [UriError]: Scheme is missing: {scheme: "", authority: "", path: "/oauth/token", query: "", fragment: ""}
```

**Comment by ak1394** [comment]
Thanks for reporting! I'll look into it.

**Comment by ak1394** [comment]
I've published an update which relaxes OAS v3 schema, removing all `"format": "uri-reference"` entries from it. I think it's a valid tradeoff for the time being.

The root of the issue lies with a schema validation library which fails to recognise relative URLs:
https://github.com/redhat-developer/yaml-language-server/issues/181 

I'm going to keep this issue open until the bug above gets resolved, and then I'll revert to the original OAS v3 schema.

**Comment by azusa0127** [comment]
Confirmed the new version 1.8.13 fixed the issue, thanks!
