### ISSUE TITLE
How to prevent $ref errors in non-openapi JSON files?

### ISSUE THREAD

**Issue by jsebrech** [42Crunch/vscode-openapi#171]
I have a project with lots of JSON files that are not OpenAPI or JSON Schema but do contain $ref properties. This extension causes errors to be shown on the lines with $ref, even though they are correct.

Is there a way to disable the automatic parsing of $ref?

Minimal example file:
```
{
    "astad-content": {
        "$ref": "astad-content"
    }
}
```

**Comment by tvharris** [comment]
I have this same problem. I have json schemas outside of the OpenAPI spec that need `$ref` relative to the root rather than relative to the file. The extension can't follow them, and marks them as problems. It would be helpful if there were a feature to disable the extension for specific files or directories. (In my case it would be even better if I could specify a base path so that the the extension can follow the `$ref`.)

**Comment by ak1394** [comment]
This issue stems from the fact that we support OpenAPI files that $ref to non OpenAPI files, which can also have $refs ie. openapi.yaml -> schemas.yaml -> schemas/user.yaml. It should be possible to check if any given file with $refs has been referred from an OpenAPI file, and try resolving $refs only in this case. I'll see if we can tackle it in one of the upcoming releases.

**Comment by ak1394** [comment]
This should be fixed in the upcoming 4.13.0 release.

**Comment by jjercx** [comment]
Is there a way to ignore a line with a special comment so we don't get errors ?

**Comment by ak1394** [comment]
@jjercx The fix is coming, so doing something like that would be unnecessary I hope.
