### ISSUE TITLE
[feature request] Option to disable "try it"

### ISSUE THREAD

**Issue by alxtz** [42Crunch/vscode-openapi#185]
<img width="659" alt="image" src="https://user-images.githubusercontent.com/16031425/191356703-551ec4f9-d9ec-48d4-9ba3-12ac9d9a7b8b.png">

I personally doesn't not find the "Try it" handle to fit our team's needs (and a bit distracting), as we use other API testing clients to fire requests

It would be nice if we could have [configs](https://github.com/42Crunch/vscode-openapi/blob/master/package.json#L793) like `openapi.tryit.enabled` to disable this for people who test their APIs in other setups. 😄

**Comment by ak1394** [comment]
Thanks for the feedback! It is a reasonable request, and I'll add an option to disable it. However since Try It is a brand new feature which I think is greeeeat :) can I ask you to share a bit more info on why you prefer to use other clients? Can we improve it somehow to make it more useful for you?

**Comment by ak1394** [comment]
Thanks for the feedback, and yes we plan to add an option to disable these codelenses, likely in a month or so.

**Comment by ak1394** [comment]
Implemented in 4.18.1 which should be released shortly.
