### ISSUE TITLE
Broken $ref support

### ISSUE THREAD

**Issue by goldsam** [42Crunch/vscode-openapi#190]
I see a number of closed issues such as #13, #21, #31, #168  (to name a few) that suggest $ref support is implemented, but this starkly contrasts with my experience.

I am using [openapi-boilerplate](https://github.com/dgarcia360/openapi-boilerplate) as a reference. This multi-file openapi project is great because it:
* validates against the openapi 3.0.0 spec 
* is simple enough to understand upon brief inspection
* sophisticated enough to represent how a real-world specification might be decomposed into multiple files

Upon opening this project in vscode, the issues with vscode-openapi are immediately clear:

1. The visual explorer only partly works while an `openapi.yaml` file is open, but is missing data which should have been resolved through `$ref`s:

![broken_ref_support](https://user-images.githubusercontent.com/5701782/197858449-9a78b0f2-412a-4142-a8de-b7a84cc81117.png)

2. Opening a file by following (i.e. control-click) a `$ref` doesn't work. The reference is followed, but then the plugin has no idea "where you are".

![follow_ref_broken](https://user-images.githubusercontent.com/5701782/197862004-f2c3d265-6983-4363-af84-3ee504a51250.gif)

3. IntelliSense doesn't work within a `$ref`ed file:

![broken_ intellisense](https://user-images.githubusercontent.com/5701782/197862885-4af9dab5-8a26-4c24-8bef-faf3e4a14668.gif)

4. Interestingly, the ReDoc and SwaggerUI previews have no problem:

![redoc_works](https://user-images.githubusercontent.com/5701782/197864322-02844730-ac18-4ce8-a28b-ce0f3c761f09.png)
![swagger-ui-works](https://user-images.githubusercontent.com/5701782/197864336-1049da7f-7502-41f4-9918-6f71b635efd1.png)

**Comment by ak1394** [comment]
Hi @goldsam !

Thanks for the feedback! There are some issues around support of multi-file OAS where we can improve, in particular around tree views, but even that requires another look at how the tree works. For example, currently the tree allows to navigate within currently open OpenAPI file by clicking on the nodes. In case of multi-file OAS, we likely will have to reflect the fact that certain operations are located in the different files and so on.

However, the openapi-boilerplate is probably not the best example on how multi-file OAS should be structured. In particular only the top-level openapi.yaml is the valid OAS, while the rest of the files is not, non of them validate against OpenAPI schema. We rely on schema for intellisence and validation, which fails for these.

We do have certain level of support for OAS structured in this way, as we "bundle" the top level file resolving all external references before passing it to SwaggerUI and ReDoc for the preview, so that's why these work.

**Comment by goldsam** [comment]
@ak1394 

> In particular only the top-level openapi.yaml is the valid OAS, while the rest of the files is not,

With all due respect, this is not true as is [state in the OAS Guid](https://swagger.io/docs/specification/using-ref/#allowed-places) as well as the official spec under [OAS: Relative References in URLs](https://swagger.io/specification/#relative-references-in-urls): 

> Unless specified otherwise, all properties that are URLs MAY be relative references as defined by [RFC3986](https://tools.ietf.org/html/rfc3986#section-4.2). Relative references are resolved using the URLs defined in the [Server Object](https://swagger.io/specification/#server-object) as a Base URI.

The OAS document is represented simply by the document entry-point, conventionally `openapi.yml` or `openapi.json`. There is no need for "the rest of the files" to be OAS documents, as the only "valid" document need be this entry-point. In fact, it doesn't really make a whole lot of sense for OAS files to be nested recursively. since each file could declare a different OAS version which would be pretty meaningless.

[openapi-boilerplate](https://github.com/dgarcia360/openapi-boilerplate) is perfectly valid as well as succinct. There should is no need to junk up spec files with superfluous `openapi: ....` statements.

**Comment by goldsam** [comment]
@ak1394 ok. I have to admit I'm a bit disappointed. I feel like this really limits the usefulness of the plugin for me and several members of my team. Thanks for engaging with me though

**Comment by ak1394** [comment]
@goldsam thanks for sharing your thoughts! I'm sorry we can't fit your requirements. I would like to offer more support OAS structured in this way (like we support it for preview and security audit) but it's not practical at this stage.
