### ISSUE TITLE
Cannot pass Bearer Token into Header in 'tryItOut' 

### ISSUE THREAD

**Issue by cleverly87** [42Crunch/vscode-openapi#209]
With the TryItOut feature - I can generate a token for the server just fine. 

Taking that token into the next http request and passing it in the header just responds with a 401. Am I missing something here?? 

Is there a particular way to write the token in or am I just coming up against non-functionality?

**Comment by ak1394** [comment]
Could you provide a sample of your OAS file? Can we test against the service you're trying to access?

**Comment by ak1394** [comment]
Did you manage to make it work? There's been a sizable update to TryIt UI, and I've confirmed that Bearer tokens work with it.

**Comment by ak1394** [comment]
Thanks for the info! There is likely a bug in a TryIt rendering UI. It would be great if you could share your OAS file, or perhaps a snippet describing the operations that would not load?

**Comment by cleverly87** [comment]
I'll provide a link to the OAS file in GitHub as it is huge. I also have to be careful as its part of a paid service. 

https://raw.githubusercontent.com/creditsafe/connect-docs/master/cs_connectv1-15.json 

there are a few items outside of the OpenAPI specification but I am slowly removing them. 

The item in question is the PATH: /companies    (GET HTTP Request) 

This is the one thats just not responding:

![image](https://user-images.githubusercontent.com/63611461/227232155-e3b75564-5eee-4dcb-a775-ff0c0478392c.png)

**Comment by ak1394** [comment]
Thanks for sharing the file, it was very helpful! The issue should be now fixed in v4.16.2. I'm going to close the ticket, but feel free to re-open it if something comes up.

Also, I noted that the "GET /companies" operation has quite a lot of query parameters. At the moment our UX is not the best  for it (we're helpfully trying to auto-generate, and end up with a lot of values), but hopefully this will soon improve.
