### ISSUE TITLE
"Array schema has no maximum number of items defined" should not be applied to parameters

### ISSUE THREAD

**Issue by simonech** [42Crunch/vscode-openapi#51]
I had a get operation with the following list of responses

```yaml
      responses:
        200:
          description: "successful operation"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/VisitRequest"
```

And I got the "Array schema has no maximum number of items defined", even with severity **High**
I don't think anyone could exploit such unbound array since it's the response from the server

**Comment by DSotnikov** [comment]
@simonech response arrays without limits can lead to data leaks.

For example, this is [what happened to the Steam gaming marketplace](https://apisecurity.io/issue-6-steam-api-leaks-keys-waf-not-help-devsecops/) when they had some sort of edge condition flaw in their code and a specific combination of inputs made their API leak thousands of game license keys instead of 1.

**Comment by simonech** [comment]
True. But all examples of code and of exploits are showing only parameters, not responses. And definitely not to be marketed as “error” but just as warning.
